name: Run Node Application

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        # run: sudo apt-get install -y nodejs
        # I want market place node copy just use below
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check Version
        run: node -v
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run check
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello World"